server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

# service URLs (important)
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8080}

tracking:
  service:
    url: ${TRACKING_SERVICE_URL:http://localhost:8081}

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8083}
